"use client";

import { useEffect, useMemo, useState } from "react";
import { Plus, RefreshCw, Search, Sparkles, TrendingDown, TrendingUp, X } from "lucide-react";

type Quote = { symbol:string; name:string; price:number; changePercent:number; entryLow:number; entryHigh:number; target2:number; target3:number; stop:number; support:number; resistance:number; rsi:number; volumeRatio:number; verdict:"ENTER"|"WAIT"|"TAKE PROFIT"|"AVOID"; trend:"Bullish"|"Neutral"|"Bearish"; sparkline:number[]; asOf:number };
const DEFAULT_SYMBOLS=["AVGO","MU","OPEN","AMD","NVDA","TSLA","PLTR","MSFT","HOOD"];
const holdings=new Set(["AVGO","MU","OPEN"]);
const money=(n:number)=>`$${n.toFixed(2)}`;

function Sparkline({values,positive}:{values:number[];positive:boolean}){if(!values.length)return null;const min=Math.min(...values),max=Math.max(...values),range=max-min||1;const points=values.map((v,i)=>`${(i/Math.max(1,values.length-1))*130},${36-((v-min)/range)*32}`).join(" ");return <svg viewBox="0 0 130 40" role="img" aria-label="Intraday price line"><polyline points={points} fill="none" stroke={positive?"#5df2ad":"#ff7081"} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg>}

export default function Home(){
 const[symbols,setSymbols]=useState(DEFAULT_SYMBOLS),[newTicker,setNewTicker]=useState(""),[quotes,setQuotes]=useState<Quote[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("All");
 async function load(list=symbols){setLoading(true);setError("");try{const response=await fetch(`/api/quotes?symbols=${list.join(",")}`,{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json();setQuotes(data.quotes||[]);if(data.errors?.length)setError(`Could not find: ${data.errors.join(", ")}`)}catch{setError("Live prices are temporarily unavailable. Tap refresh to retry.")}finally{setLoading(false)}}
 useEffect(()=>{const saved=localStorage.getItem("smart-sally-tickers");if(saved){try{const list=JSON.parse(saved);if(Array.isArray(list)&&list.length)setSymbols(list)}catch{}}},[]);
 useEffect(()=>{load(symbols);const id=setInterval(()=>load(symbols),180000);return()=>clearInterval(id)},[symbols]);
 function addTicker(){const ticker=newTicker.trim().toUpperCase();if(!/^[A-Z][A-Z0-9.-]{0,9}$/.test(ticker)){setError("Enter a valid US ticker, e.g. AAPL");return}if(symbols.includes(ticker)){setError(`${ticker} is already on your board`);return}const next=[...symbols,ticker].slice(0,18);setSymbols(next);localStorage.setItem("smart-sally-tickers",JSON.stringify(next));setNewTicker("");setError("")}
 function removeTicker(ticker:string){const next=symbols.filter(s=>s!==ticker);setSymbols(next);localStorage.setItem("smart-sally-tickers",JSON.stringify(next))}
 const filtered=useMemo(()=>quotes.filter(q=>`${q.symbol} ${q.name}`.toLowerCase().includes(query.toLowerCase())&&(filter==="All"||(filter==="My holdings"&&holdings.has(q.symbol))||q.verdict===filter.toUpperCase())),[quotes,query,filter]);
 const best=[...quotes].sort((a,b)=>(b.trend==="Bullish"?2:0)+b.volumeRatio-((a.trend==="Bullish"?2:0)+a.volumeRatio))[0],bullish=quotes.filter(q=>q.trend==="Bullish").length;
 return <main className="shell">
  <header className="topbar"><div className="brand"><div className="moon">S</div><div><strong>SMART SALLY</strong><span>MOON HOLDINGS</span></div></div><div className="market"><i/> US MARKET <span>LIVE</span></div><button className="refresh" onClick={()=>load()} disabled={loading}><RefreshCw className={loading?"spin":""} size={17}/> Refresh</button></header>
  <section className="hero"><div><p className="eyebrow"><Sparkles size={14}/> TODAY&apos;S SCALP DESK</p><h1>Small moves.<br/><em>Clean exits.</em></h1><p className="lede">A focused 2–3% daily trade view for Sally&apos;s top US names.</p></div><div className="brief"><div className="brief-label">BEST SETUP NOW</div>{best?<><div className="best-row"><b>{best.symbol}</b><span className={`pill ${best.verdict.toLowerCase().replace(" ","-")}`}>{best.verdict}</span></div><p>{best.trend} tape · {best.volumeRatio.toFixed(1)}× volume</p><div className="brief-levels"><span>ENTRY <b>{money(best.entryLow)}–{money(best.entryHigh)}</b></span><span>+3% <b>{money(best.target3)}</b></span></div></>:<div className="skeleton wide"/>}</div></section>
  <section className="metrics"><div><span>WATCHING</span><b>{quotes.length||9}</b><small>top US names</small></div><div><span>BULLISH TAPE</span><b>{bullish}</b><small>of {quotes.length||9} tickers</small></div><div><span>PLAYBOOK</span><b>2–3%</b><small>daily target</small></div><div><span>AUTO REFRESH</span><b>3m</b><small>{quotes[0]?`as of ${new Date(quotes[0].asOf*1000).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}`:"live session"}</small></div></section>
  <section className="controls"><div className="tabs">{["All","My holdings","Enter","Wait","Avoid"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="tools"><label className="add"><Plus size={16}/><input value={newTicker} onChange={e=>setNewTicker(e.target.value.toUpperCase())} onKeyDown={e=>e.key==="Enter"&&addTicker()} placeholder="Add ticker" maxLength={10}/><button onClick={addTicker}>Add</button></label><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find ticker"/></label></div></section>
  {error&&<div className="notice">{error}</div>}
  <section className="grid">{loading&&!quotes.length?symbols.map(s=><div className="card loading" key={s}><div className="skeleton title"/><div className="skeleton price"/><div className="skeleton wide"/><div className="skeleton wide"/></div>):filtered.map(q=>{const up=q.changePercent>=0,isCustom=!DEFAULT_SYMBOLS.includes(q.symbol);return <article className="card" key={q.symbol}>{isCustom&&<button className="remove" onClick={()=>removeTicker(q.symbol)} title={`Remove ${q.symbol}`} aria-label={`Remove ${q.symbol}`}><X size={14}/></button>}<div className="card-head"><div className="ticker"><div className="logo">{q.symbol.slice(0,2)}</div><div><h2>{q.symbol}{holdings.has(q.symbol)&&<sup>HELD</sup>}</h2><p>{q.name}</p></div></div><span className={`pill ${q.verdict.toLowerCase().replace(" ","-")}`}>{q.verdict}</span></div><div className="price-row"><div><strong>{money(q.price)}</strong><span className={up?"up":"down"}>{up?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {up?"+":""}{q.changePercent.toFixed(2)}%</span></div><Sparkline values={q.sparkline} positive={up}/></div><div className="entry"><span>IDEAL ENTRY ZONE</span><b>{money(q.entryLow)} <i>→</i> {money(q.entryHigh)}</b></div><div className="targets"><div><span>TAKE PROFIT 1</span><b>{money(q.target2)}</b><small>+2%</small></div><div><span>TAKE PROFIT 2</span><b>{money(q.target3)}</b><small>+3%</small></div><div className="stop"><span>STOP</span><b>{money(q.stop)}</b><small>protect capital</small></div></div><div className="signals"><span>RSI <b>{q.rsi.toFixed(0)}</b></span><span>VOL <b>{q.volumeRatio.toFixed(1)}×</b></span><span>TREND <b className={q.trend.toLowerCase()}>{q.trend}</b></span></div><div className="range"><span>Support {money(q.support)}</span><span>Resistance {money(q.resistance)}</span></div></article>})}</section>
  <footer><p>Targets are generated from recent price action, momentum and volume—not financial advice. Confirm the setup after the US market opens and use your stop.</p><span>Smart Sally · v2</span></footer>
 </main>
}
