const NAMES:Record<string,string>={AVGO:"Broadcom",MU:"Micron",OPEN:"Opendoor",AMD:"Advanced Micro Devices",NVDA:"NVIDIA",TSLA:"Tesla",PLTR:"Palantir",MSFT:"Microsoft",HOOD:"Robinhood"};
function ema(values:number[],period:number){const k=2/(period+1);return values.reduce((a,v,i)=>i?v*k+a*(1-k):v,values[0]||0)}
function rsi(values:number[],period=14){if(values.length<period+1)return 50;let g=0,l=0;for(let i=values.length-period;i<values.length;i++){const d=values[i]-values[i-1];if(d>0)g+=d;else l-=d}return l===0?75:100-(100/(1+g/l))}
const round=(n:number)=>Math.round(n*100)/100;
async function quote(symbol:string){
 const url=`https://query1.finance.yahoo.com/v8/finance/chart/${symbol}?interval=5m&range=5d&includePrePost=true`,res=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0"}});if(!res.ok)throw new Error(symbol);
 const json:any=await res.json(),result=json.chart?.result?.[0];if(!result)throw new Error(symbol);
 const timestamps:number[]=result.timestamp||[],q=result.indicators?.quote?.[0]||{},rows=timestamps.map((t,i)=>({t,close:q.close?.[i],high:q.high?.[i],low:q.low?.[i],volume:q.volume?.[i]})).filter(x=>Number.isFinite(x.close));if(rows.length<20)throw new Error(symbol);
 const closes=rows.map(x=>x.close as number),recent=rows.slice(-78),last=closes.at(-1) as number,meta=result.meta||{},prev=meta.chartPreviousClose||meta.previousClose||closes[0],lows=recent.map(x=>x.low).filter(Number.isFinite) as number[],highs=recent.map(x=>x.high).filter(Number.isFinite) as number[],support=Math.min(...lows),resistance=Math.max(...highs),e9=ema(closes.slice(-60),9),e20=ema(closes.slice(-60),20),strength=rsi(closes),vols=recent.map(x=>x.volume||0),avgVol=vols.slice(0,-1).reduce((a,b)=>a+b,0)/Math.max(1,vols.length-1),volRatio=(vols.at(-1)||0)/(avgVol||1),entryMid=Math.min(last,support+(resistance-support)*.28),entryLow=entryMid*.997,entryHigh=entryMid*1.003,trend=e9>e20*1.001?"Bullish":e9<e20*.999?"Bearish":"Neutral";
 let verdict:"ENTER"|"WAIT"|"TAKE PROFIT"|"AVOID"="WAIT";if(strength>74||last>=resistance*.998)verdict="TAKE PROFIT";else if(trend==="Bullish"&&strength>=45&&strength<=68&&last<=entryHigh*1.005)verdict="ENTER";else if(trend==="Bearish"&&strength<42)verdict="AVOID";
 return{symbol,name:NAMES[symbol]||meta.shortName||meta.longName||symbol,price:round(last),changePercent:round((last/prev-1)*100),entryLow:round(entryLow),entryHigh:round(entryHigh),target2:round(entryHigh*1.02),target3:round(entryHigh*1.03),stop:round(Math.min(entryLow*.985,support*.997)),support:round(support),resistance:round(resistance),rsi:round(strength),volumeRatio:round(volRatio),verdict,trend,sparkline:closes.slice(-28).map(round),asOf:rows.at(-1)?.t||Math.floor(Date.now()/1000)}
}
export async function GET(request:Request){const symbols=(new URL(request.url).searchParams.get("symbols")||"").split(",").map(x=>x.trim().toUpperCase()).filter(x=>/^[A-Z][A-Z0-9.-]{0,9}$/.test(x)).slice(0,18),settled=await Promise.allSettled(symbols.map(quote));return Response.json({quotes:settled.filter(x=>x.status==="fulfilled").map((x:any)=>x.value),errors:settled.map((x,i)=>x.status==="rejected"?symbols[i]:null).filter(Boolean)},{headers:{"Cache-Control":"public, max-age=45"}})}
