const CORE=["AVGO","MU","OPEN","AMD","NVDA","TSLA","PLTR","MSFT","HOOD","AAPL","GOOGL","AMZN","META","UBER","CRWV","CRCL","LIDR","CB","SPCX"],KEY="smart-sally-github-tickers";
let saved=[];try{saved=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{}
const initial=[...new Set([...CORE,...(Array.isArray(saved)?saved:[])])];
const state={scan:null,tickers:initial,filter:"ALL",query:""};
localStorage.setItem(KEY,JSON.stringify(initial));
const $=s=>document.querySelector(s),money=n=>`$${Number(n).toFixed(2)}`;
function pill(v){return v.toLowerCase().replaceAll(" ","-")}
function spark(values,up){if(!values?.length)return"";const min=Math.min(...values),max=Math.max(...values),r=max-min||1,p=values.map((v,i)=>`${i/(values.length-1)*130},${36-(v-min)/r*32}`).join(" ");return `<svg viewBox="0 0 130 40"><polyline points="${p}" fill="none" stroke="${up?'#5df2ad':'#ff7081'}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`}
function bySymbol(){return new Map(state.scan.quotes.map(q=>[q.symbol,q]))}
function render(){const map=bySymbol(),stocks=state.tickers.map(s=>map.get(s)).filter(Boolean).filter(q=>(state.filter==="ALL"||q.verdict===state.filter)&&`${q.symbol} ${q.name}`.toLowerCase().includes(state.query));$("#watching").textContent=state.tickers.length;$("#bullish").textContent=state.scan.quotes.filter(q=>q.trend==="Bullish").length;$("#updated").textContent=state.scan.updatedShort;$("#grid").innerHTML=stocks.map(q=>{const up=q.changePercent>=0,custom=!CORE.includes(q.symbol);return `<article class="card">${custom?`<button class="remove" data-remove="${q.symbol}" title="Remove ${q.symbol}">×</button>`:""}<div class="card-head"><div class="ticker"><i>${q.symbol.slice(0,2)}</i><span><b>${q.symbol}</b><small>${q.name}</small></span></div><strong class="pill ${pill(q.verdict)}">${q.verdict}</strong></div><div class="price"><span><b>${money(q.price)}</b><small class="${up?'up':'down'}">${up?'+':''}${q.changePercent.toFixed(2)}%</small></span>${spark(q.sparkline,up)}</div><div class="entry"><small>IDEAL ENTRY ZONE</small><b>${money(q.entryLow)} → ${money(q.entryHigh)}</b></div><div class="targets"><span><small>TAKE PROFIT 1</small><b>${money(q.target2)}</b><em>+2%</em></span><span><small>TAKE PROFIT 2</small><b>${money(q.target3)}</b><em>+3%</em></span><span><small>STOP</small><b>${money(q.stop)}</b><em class="red">protect capital</em></span></div><div class="signals"><span>RSI <b>${q.rsi.toFixed(0)}</b></span><span>VOL <b>${q.volumeRatio.toFixed(1)}×</b></span><span>TREND <b class="${q.trend.toLowerCase()}">${q.trend}</b></span></div><div class="range"><span>Support ${money(q.support)}</span><span>Resistance ${money(q.resistance)}</span></div></article>`}).join("")||`<div class="empty">No matching stocks in this scan.</div>`;renderBest()}
function renderBest(){const choices=state.scan.quotes.filter(q=>state.tickers.includes(q.symbol)).sort((a,b)=>(b.trend==="Bullish"?2:0)+b.volumeRatio-((a.trend==="Bullish"?2:0)+a.volumeRatio)),q=choices[0];if(!q)return;$("#best").innerHTML=`<small>BEST SETUP NOW</small><div class="best-row"><b>${q.symbol}</b><strong class="pill ${pill(q.verdict)}">${q.verdict}</strong></div><p>${q.trend} tape · ${q.volumeRatio.toFixed(1)}× volume</p><div class="best-levels"><span>ENTRY<b>${money(q.entryLow)}–${money(q.entryHigh)}</b></span><span>+3%<b>${money(q.target3)}</b></span></div>`}
function addTicker(){const s=$("#addTicker").value.trim().toUpperCase(),map=bySymbol();if(!map.has(s)){show(`Ticker ${s||'?'} is not in the current scan universe`);return}if(!state.tickers.includes(s))state.tickers.push(s);localStorage.setItem(KEY,JSON.stringify(state.tickers));$("#addTicker").value="";render();show(`${s} added`)}
function show(t){$("#notice").textContent=t;setTimeout(()=>$("#notice").textContent="",2600)}
async function load(){try{const r=await fetch(`scan.json?v=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw 0;state.scan=await r.json();render()}catch{$("#notice").textContent="Market scan is updating. Refresh again shortly."}}
$("#filters").addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;state.filter=b.dataset.filter;document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));render()});$("#search").addEventListener("input",e=>{state.query=e.target.value.toLowerCase();render()});$("#addButton").addEventListener("click",addTicker);$("#addTicker").addEventListener("keydown",e=>e.key==="Enter"&&addTicker());$("#refresh").addEventListener("click",load);$("#grid").addEventListener("click",e=>{const s=e.target.dataset.remove;if(!s)return;state.tickers=state.tickers.filter(x=>x!==s);localStorage.setItem(KEY,JSON.stringify(state.tickers));render()});load();setInterval(load,180000);
